### PR TITLE
fuck you virt

### PR DESCRIPTION
**Pull request by Apethesis**

### CODE REVIEW

**Comment by ghost** [comment]
This is useless, I'd rather have a command that sends furry porn. Plus, you didn't even register the command

**Comment by bananasov** [comment]
> This is useless, I'd rather have a command that sends furry porn. Plus, you didn't even register the command

I'm on it :trollface:

**Comment by fatboychummy** [comment]
> > This is useless, I'd rather have a command that sends furry porn. Plus, you didn't even register the command
> 
> I'm on it :trollface:

I've yet to see a fork with this implemented. Where's our furry porn command?

**Comment by bananasov** [comment]
> > > This is useless, I'd rather have a command that sends furry porn. Plus, you didn't even register the command
> > 
> > 
> > I'm on it :trollface:
> 
> I've yet to see a fork with this implemented. Where's our furry porn command?

Too busy wanking to said material

**Pull request closed without merging**
